require 'rspec'
require_relative '../lib/tfoutputs/configurator/state_reader'
require_relative '../lib/tfoutputs/configurator/state_configurator'
require_relative '../lib/tfoutputs/configurator/s3_state_configuration'
require_relative '../lib/tfoutputs/configurator/file_state_configuration'
